// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkNtiVS7wIY6tvhlOa4SoO_srqqBAsu6c',
    appId: '1:691206438005:web:30630968ad3a7a18350c3c',
    messagingSenderId: '691206438005',
    projectId: 'reedinook',
    authDomain: 'reedinook.firebaseapp.com',
    storageBucket: 'reedinook.appspot.com',
    measurementId: 'G-M7FXEJZHW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiFKcmgVnX0LDUS0YMNz2GusmlG7xRuWk',
    appId: '1:691206438005:android:d9de35d0e811d960350c3c',
    messagingSenderId: '691206438005',
    projectId: 'reedinook',
    storageBucket: 'reedinook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCurgzkegga07FFVVJ3uuTVXvrPnE3Yq5Q',
    appId: '1:691206438005:ios:7c7120db8199d871350c3c',
    messagingSenderId: '691206438005',
    projectId: 'reedinook',
    storageBucket: 'reedinook.appspot.com',
    iosBundleId: 'com.example.reedinook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCurgzkegga07FFVVJ3uuTVXvrPnE3Yq5Q',
    appId: '1:691206438005:ios:7c7120db8199d871350c3c',
    messagingSenderId: '691206438005',
    projectId: 'reedinook',
    storageBucket: 'reedinook.appspot.com',
    iosBundleId: 'com.example.reedinook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkNtiVS7wIY6tvhlOa4SoO_srqqBAsu6c',
    appId: '1:691206438005:web:7558a4e18b20827a350c3c',
    messagingSenderId: '691206438005',
    projectId: 'reedinook',
    authDomain: 'reedinook.firebaseapp.com',
    storageBucket: 'reedinook.appspot.com',
    measurementId: 'G-QP1J36KRZG',
  );
}
